import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { QueryProvider } from "@/components/providers/query-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-dvh bg-background text-foreground">
        <QueryProvider>
            <ThemeProvider defaultTheme="system">
            <div className="relative min-h-dvh overflow-x-hidden bg-[radial-gradient(circle_at_top_left,_var(--color-muted)_0%,_transparent_35%),radial-gradient(circle_at_top_right,_var(--color-accent)_0%,_transparent_30%)] dark:bg-[radial-gradient(circle_at_top_left,_color-mix(in_oklch,var(--color-primary)_12%,transparent)_0%,_transparent_35%),radial-gradient(circle_at_top_right,_color-mix(in_oklch,var(--color-primary)_10%,transparent)_0%,_transparent_28%)]">
              {children}
            </div>
            <Toaster />
          </ThemeProvider>
        </QueryProvider>
       
      </body>
    </html>
  );
}
